import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * A collection of methods used for cracking Merkle's puzzles
 * @author Thomas Fisher, James Parry-Turner
 */
public class Cracking {
	
	private static final int NUM_OF_ZERO_BYTES = 16;
	private static final int KEY_ZERO_BYTES = 6;
	private static final int KEY_BITS_SIZE = 16;
	private static final int START_OF_KEY = 18;
	private static final int END_OF_KEY = 26;
	private static final int START_OF_PUZZLE_NO = 16;
	private static final int END_OF_PUZZLE_NO = 18;
	
	/**
	 * Runs through the cracking process to crack a random puzzle that was generated
	 * using the Merkle's puzzles cryptographic approach.
	 * @return The unique puzzle number of the cracked puzzle
	 * @throws IOException
	 */
	public int crackingProcess() throws IOException {
		// Choose random puzzle
		String puzzle = randomPuzzle();
		System.out.println("Cracking puzzle: " + puzzle);
		
		// Crack the puzzle by brute force
		String crackedPuzzle = crack(puzzle);
		
		// Get the puzzle number in a byte array of the cracked puzzle
		byte[] puzzleNoBytes = extractPuzzleNo(crackedPuzzle);
		
		// Convert the puzzle number into an integer
		int puzzleNumber = CryptoLib.byteArrayToSmallInt(puzzleNoBytes);
		
		// Print the puzzle number
		System.out.println("Puzzle Number: " + puzzleNumber);
		
		// Extract the key from the cracked puzzle
		byte[] keyBytes = extractKey(crackedPuzzle);
		
		// Convert the key from byte array to string
		String plaintextKey = CryptoLib.byteArrayToString(keyBytes);
		
		// Print the key
		System.out.println("Plaintext Key: " + plaintextKey);
		
		return puzzleNumber;
	}
	
	/**
	 * Crack a plaintext puzzle by brute force, trying all possible keys (2^16) until the correct key 
	 * is found. This is found by looking for the key which starts with 128 zero bits.
	 * @param puzzle, a string of a puzzle in plaintext that will be cracked
	 * @return Decrypted puzzle
	 * @throws IOException
	 */
	public static String crack(String puzzle) throws IOException {
		ArrayList<String> plaintextPuzzles = new ArrayList<String>();
		
		String crackedPuzzle = "N/A";
		
		// For every possible key (2^16), try decrypting the puzzle
		for (int i=0; i<Math.pow(2, KEY_BITS_SIZE); i++) {
			// Get the byte array of the current index
			byte[] keyBits = CryptoLib.smallIntToByteArray(i);
			
			// Generate 6 bytes of zeros for the end of the key
			byte[] zeros = new byte[KEY_ZERO_BYTES];
			
			// Concatenate the key bits and the zero bits
			byte[] key = buildKey(keyBits, zeros);
			
			// Try decrypting the puzzle
			try {
				byte[] decryptedPuzzle = new DES().decrypt(puzzle, CryptoLib.createKey(key));
				
				// If decrypting was successful, add the decrypted puzzle to the list of possible puzzles
				plaintextPuzzles.add(CryptoLib.byteArrayToString(decryptedPuzzle));
			} catch (Exception e) {
				// Invalid key
			}
		}
		
		plaintextPuzzles = removeDuplicates(plaintextPuzzles);
	
		// Look for a puzzle with 128 zero bits at the start
		for (String elem: plaintextPuzzles) {
			byte[] puzzleBytes = CryptoLib.stringToByteArray(elem);
			
			byte[] zeros = new byte[NUM_OF_ZERO_BYTES];
			byte[] zerosPart = Arrays.copyOfRange(puzzleBytes, 0, NUM_OF_ZERO_BYTES);
			
			if (Arrays.equals(zerosPart, zeros)) {
				// Select this puzzle as the cracked puzzle
				crackedPuzzle = elem;
				// Print the cracked puzzle
				System.out.println("Cracked plaintext: " + elem);
			}
		}
		
		return crackedPuzzle;
	}
	
	/**
	 * Build a byte array representing a key by concatenating pre-generated key bits with 48 zero bits
	 * @param Pre-generated byte array of key bits
	 * @param Byte array of 48 zero bits
	 * @return A 64 bit key consisting of an initial 16 key bits followed by 48 zero bits
	 * @throws IOException
	 */
	private static byte[] buildKey(byte[] keyBits, byte[] zeros) throws IOException {
		ByteArrayOutputStream stream = new ByteArrayOutputStream();
		stream.write(keyBits);
		stream.write(zeros);
		return stream.toByteArray();
	}
	
	/**
	 * Remove duplicate entries in an ArrayList of Strings
	 * @param ArrayList of Strings which may include duplicates
	 * @return ArrayList of Strings with no duplicate entries in it
	 */
	private static ArrayList<String> removeDuplicates(ArrayList<String> list) {
		Set<String> cleanDuplicates = new HashSet<>(); // Set data-type used to remove duplicates
		
		// Remove duplicate puzzles
		cleanDuplicates.addAll(list);
		list.clear();
		list.addAll(cleanDuplicates);
		
		return list;
	}
	
	/**
	 * Extracts the key part from a plaintext puzzle by taking the last 8 bytes (64 bits)
	 * @param The string puzzle as plaintext to extract a key from
	 * @return The key part of the puzzle as a byte array
	 */
	public static byte[] extractKey(String puzzle)  {
		byte[] puzzleBytes = CryptoLib.stringToByteArray(puzzle);
		
		return Arrays.copyOfRange(puzzleBytes, START_OF_KEY, END_OF_KEY);
	}
	
	/**
	 * Extracts the unique puzzle number part from a plaintext puzzle by taking the 
	 * 2 bytes (16 bits) that hold the puzzle number
 	 * @param The string puzzle as plaintext to extract a key from
	 * @return The key part of the puzzle as a byte array
	 */
	public static byte[] extractPuzzleNo(String puzzle) {
		byte[] puzzleBytes = CryptoLib.stringToByteArray(puzzle);
		
		return Arrays.copyOfRange(puzzleBytes, START_OF_PUZZLE_NO, END_OF_PUZZLE_NO);
	}
	
	/**
	 * Runs through a file of string puzzles and extracts a random puzzle
	 * @return A random puzzle from puzzles.txt
	 * @throws IOException
	 */
	public static String randomPuzzle() throws IOException {
		String[] puzzles = readPuzzleFile("puzzles.txt");
		String puzzle = puzzles[(int)(Math.random() * puzzles.length)];
		return puzzle;
	}
	
	/**
	 * Reads through a file and puts the lines into an array
	 * @param The filepath as a string of the file to read
	 * @return An array of every line in a file
	 * @throws IOException
	 */
	public static String[] readPuzzleFile(String filepath) throws IOException {
		BufferedReader reader = new BufferedReader(new FileReader(filepath));	
		List<String> lines = new ArrayList<String>();
		String line = null;
        
        while ((line = reader.readLine()) != null) {
        	lines.add(line);
        }
        
        reader.close();
        
        return lines.toArray(new String[lines.size()]);
	}
	
}
